### ISSUE TITLE
[Request] Release a Fabric version compatible with 1.18.2

### ISSUE THREAD

**Issue by GoldenFurredFox** [nad2040/Elytra-Bombing-Mod#11]
1.18.1 and 1.18.2 both use fairly similar code-bases on Fabric, and while I don't know the precise level of your code, most mods require minimal changes to be compatible with 1.18.2 when coming from 1.18.1.

If this would be too difficult for you, then by all means, don't do it, but I'd really like to be able to use Elytra Bombing within my Fabric 1.18.2 mod pack.

**Comment by nad2040** [comment]
I believe I tried before. The tnt with flint and steel works, but the anvil entity just immediately despawns/disappears and I still don't understand why. I'm going to try a couple of things to see if I can figure out why.

**Comment by nad2040** [comment]
I have figured it out and I've made a new release. I've tested it myself, but let me know if it works for you.

**Comment by GoldenFurredFox** [comment]
Sorry, forgot to send an update right away.

I couldn't upload the video directly here, so it's on YouTube (video deleted).

Anvils seemed to work fine, as did TNT, though I couldn't seem to throw Anvils whilst I had the Flint and Steel in my offhand. This may warrant more testing to see what other offhand items, if any, prevent the placement of Anvils, but I'll leave the final judgement of that up to you.

Thanks for being so fast about all this, I really appreciate it. Love this mod.

**Comment by nad2040** [comment]
Ah, that is intended. If you look at the README you’ll see

> if you hold just an anvil and no item in your other hand

I had originally thought about trying to see if I could use the pose for holding a map in both hands but instead using an anvil. I never decided to bother implementing that.

I can add an option to allow you to drop anvils with items in the other hand.

**Comment by GoldenFurredFox** [comment]
Edit: The page didn't load your response. I'm sorry.

**Comment by GoldenFurredFox** [comment]
> [...]
> 
> I can add an option to allow you to drop anvils with items in the other hand.

At the very least, it might be nice to have an option to drop them with a shield, torch, totem, or food item in the off-hand, but if it'd be easier to add support for everything than just adding a whitelist, then go ahead with that instead.

**Comment by nad2040** [comment]
Can you try the newest release? I just removed the condition entirely and I no longer think it fits.

Now the game will decide which item with right click actions has priority, so you might have to hold the anvils in the main hand for it to work.

**Comment by GoldenFurredFox** [comment]
@nad2040 Sorry again for not getting around to this right away.

I have tested your mod again, and the second upload is also on YouTube (video deleted) now, since I also couldn't upload it directly here.

Things seem to work regardless of main- or offhand so long as the thing in your other hand doesn't have a general in-air use case, meaning that the item can't have a use while clicking away from a block. Given how the system tends to work in this footage, I'd likely assume that the same applies to things that have uses on blocks if you're looking at the necessary block while flying, making the TNT also not drop in that case.

**Comment by nad2040** [comment]
I'm a little confused as to what you want changed specifically. I noticed that you're making an assumption.

In your video, you hold the fishing rod, spyglass, and water bottle (consumable) in your main hand with an anvil in the offhand. In these cases, as I mentioned in my previous message, you'll probably need to swap the anvil into the main hand for it to work. I'm a little confused by the description saying "it seems that you cannot drop anvils to the ground with a flint and steel in your offhand" when you showcase that exact thing in the video. Is that a typo?

I'm probably not going to change any of the behavior present because it likely can't be changed. It happens because I'm injecting the code at the end of the method, so any actions from other items take precedent. I remember changing the code from injecting at the beginning of the method to injecting at the end and it fixed some problems. I can test the behavior after changing it back to inject at head later today, but I still think the current behavior is fine.

**Comment by GoldenFurredFox** [comment]
@nad2040 I apologize for the confusion. You'd asked me to test it prior, so I was giving it another test and ensuring everything worked as you intended. Based on what you've said, it is indeed working as you intended. I just wanted to confirm that with you since you said before that you have little time to test things yourself. I am satisfied with how the mod is working, and if you'd like to close this ticket, you may.

**Comment by nad2040** [comment]
Ah, thanks for the clarification. I actually am not too busy at the moment. I'm glad to hear that you're satisfied. Have a good day.
